services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    container_name: zenfy-api
    ports:
      - "3000:3000"
    environment:
      - GO_ENV=development
    env_file:
      - .env
    working_dir: /src
    volumes:
      - .:/src
      - /go/pkg/mod
    command: []
    depends_on:
      db:
        condition: service_healthy
      mail:
        condition: service_healthy

  db:
    image: postgres:18.1-alpine
    container_name: zenfy-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=zenfyuser
      - POSTGRES_PASSWORD=zenfypassword
      - POSTGRES_DB=zenfydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mail:
    image: axllent/mailpit:latest
    container_name: zenfy-mailpit
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
    environment:
      - MAILPIT_SMTP_BIND_ADDR=0.0.0.0:1025
      - MAILPIT_UI_BIND_ADDR=0.0.0.0:8025
      - MAILPIT_SMTP_AUTH=true
      - MAILPIT_SMTP_AUTH_USERNAME=zenfyuser
      - MAILPIT_SMTP_AUTH_PASSWORD=zenfypassword
      - MAILPIT_UI_AUTH=true
      - MAILPIT_UI_USERNAME=zenfyuser
      - MAILPIT_UI_PASSWORD=zenfypassword
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 1025 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: